baseURL = "https://deven.tw"
languageCode = 'en-us'
title = "DevenTW"
theme = "yinyang"
DefaultContentLanguage = "en"
enableRobotsTXT = true
canonifyURLs = false

[related]
includeNewer = true
threshold = 80
toLower = false
[[related.indices]]
name = "date"
weight = 100
[[related.indices]]
name = "keywords"
weight = 100

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "tango"
    tabWidth = 2


[author]
  name = "DevenTW"
  homepage = "https://deventw.com/"

# [languages]
#   [languages.en]
#     contentDir = "content/en"
#     languageName = "English"
#     weight = 1
#   [languages.cn]
#     contentDir = "content/cn"
#     languageName = "Chinese"
#     weight = 1

[permalinks]
    post = "/blog/:title/"



[params]
headTitle = "DEVENTW"
description = "YOLO."
favicon = "/logo.png"
mainSections = ["posts"]

# Google Analytics 4
googleAnalyticsID = "G-YMVW1G7LXS"

postHeaderContent = ""
# postFooterContent = '<br/><br/><p>Subscribe：<a target="_blank" href="https://mailchi.mp/a1a0d59e7a19/dev"><b>Mailchimp</b></a></p><br/><a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://blog.joway.io/images/cc.png" /></a>'
disqus = "deventw" # disqus account name
extraHead = ""
# extraBody = ''
# postAds = ''
lazyImage = true
# [[params.socials]]
# name = "Telegram"
# link = "https://t.me/XXX"


# [[params.socials]]
# name = "RSS"
# link = "/index.xml"

# [[params.socials]]
# name = "Slides"
# link = "/presentations"



[[params.socials]]
name = "Github"
link = "https://github.com/deventw"

# [[params.socials]]
# name = "Subscribe"
# link = "https://mailchi.mp/a1a0d59e7a19/deventw"
# [[params.socials]]
# name = "Travel"
# link = "/travel"
[[params.socials]]
name = "About"
link = "https://deven.tw"

